name: migra_chat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  country_flags: ^2.2.0
  country_pickers: ^2.0.0
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  form_builder_validators: ^9.1.0
  getwidget: ^4.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  tflite_flutter: ^0.10.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/country_flags/
