name: migra_chat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  country_flags: ^2.2.0
  country_pickers: ^2.0.0
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  getwidget: ^4.0.0
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/country_flags/
